<?php

/**
 * Test class for Application_Model_FlowerMapper.
 * Generated by PHPUnit on 2012-07-23 at 12:50:50.
 */
class Application_Model_FlowerMapperTest extends MapperTestCase
{

	protected $_initialSeedFile = 'flowers.xml';

	/**
	 * @var Application_Model_FlowerMapper
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		parent::setUp();
		$this->object = new Application_Model_FlowerMapper();
	}

	public function testCanCreateFlowerMapper()
	{
		$this->assertInstanceOf('Standard_Mapper_Abstract', $this->object);
		$this->assertInstanceOf('Application_Model_FlowerMapper', $this->object);
	}

	public function testCanGetTable()
	{
		$this->assertInstanceOf('Application_Model_DbTable_Flowers', $this->object->getDbTable());
	}

	public function testCanFindFlower()
	{
		$flower	  = $this->object->find(1);
		$this->assertInstanceOf('Application_Model_Flower', $flower);
		$flowerArray = array(
			'id'		 => $flower->getId(),
			'position_x' => $flower->getPosition_x(),
			'position_y' => $flower->getPosition_y(),
			'status'	 => $flower->getStatus(),
			'modified'   => $flower->getModified(),
			'created'	=> $flower->getCreated(),
		);
		$this->_dataSet = $this->convertRecordToDataSet($flowerArray, 'flowers');
		$this->assertDataSetsMatchXML('flowersFoundOne.xml', $this->_dataSet);

		$flowerNotFound = $this->object->find(99);
		$this->assertFalse($flowerNotFound);
	}

	/**
	 *@todo Fetchall Assertion
	 */
	public function testCanFetchAll()
	{
//		$flowers = $this->object->fetchAll();

		$this->assertFalse($this->object->fetchAll(array('id=?' => 9999)));
	}

}

?>
