<?php

/**
 * Test class for Application_Model_DbTable_Users.
 * Generated by PHPUnit on 2012-07-14 at 08:06:43.
 */
class Application_Model_DbTable_FlowersTest extends ControllerTestCase {

	public function testCanCreateDbTableFlowers() {
		$flower = new Application_Model_DbTable_Flowers();
		$this->assertInstanceOf('Application_Model_DbTable_Flowers', $flower);
	}

	public function testDbTableUsersHasAttributes() {
		$flower = new Application_Model_DbTable_Flowers();
		$this->assertObjectHasAttribute('_name', $flower);
		$this->assertAttributeEquals('flowers', '_name', $flower);
	}

}

?>
