<?php

/**
 * Test class for Application_Model_DbTable_Users.
 * Generated by PHPUnit on 2012-07-14 at 08:06:43.
 */
class Application_Model_DbTable_UsersTest extends ControllerTestCase {

	public function testCanCreateDbTableUsers() {
		$user = new Application_Model_DbTable_Users();
		$this->assertInstanceOf('Application_Model_DbTable_Users', $user);
	}

	public function testDbTableUsersHasAttributes() {
		$user = new Application_Model_DbTable_Users();
		$this->assertObjectHasAttribute('_name', $user);
		$this->assertAttributeEquals('users', '_name', $user);
	}

}

?>
