<?php

/**
 * Test class for Application_Model_DbTable_Users.
 * Generated by PHPUnit on 2012-07-14 at 08:06:43.
 */
class Application_Model_DbTable_UsersTest extends Zend_Test_PHPUnit_ControllerTestCase {

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->bootstrap = new Zend_Application(APPLICATION_ENV, APPLICATION_PATH . '/configs/application.ini');
		parent::setUp();
	}

	public function testCanCreateDbTableUsers() {
		$user = new Application_Model_DbTable_Users();
		$this->assertInstanceOf('Application_Model_DbTable_Users', $user);
	}

	public function testDbTableUsersHasAttributes() {
		$user = new Application_Model_DbTable_Users();
		$this->assertObjectHasAttribute('_name', $user);
		$this->assertAttributeEquals('users', '_name', $user);
	}

}

?>
